package:
  format-version: "1.0.0"
  name: "reference_apps_sam_mcu"
  type: "application"
  status: "production"
  required: false
  version: "1.0.0"

  dependencies:
    - name: "csp"
      type: "package"
      version: "v3.20.0"
    - name: "core"
      type: "package"
      version: "v3.14.1"
    - name: "bsp"
      type: "package"
      version: "3.21.1"
    - name: "usb"
      type: "package"
      version: "v3.15.0"
    - name: "gfx"
      type: "package"
      version: "3.15.3"
    - name: "touch"
      type: "package"
      version: "v3.17.0"
    - name: "net"
      type: "package"
      version: "v3.13.0"
    - name: "wireless_wifi"
      type: "package"
      version: "v3.12.0"
    - name: "FreeRTOS-Kernel"
      type: "package"
      version: "v11.1.0"
    - name: "wolfssl"
      type: "package"
      version: "v5.7.0"
    - name: "crypto"
      type: "package"
      version: "v3.8.2"
    - name: "cryptoauthlib"
      type: "package"
      version: "v3.7.6"
    - name: "wireless_rnbd"
      type: "package"
      version: "v2.0.4"
