package:
  format-version: "1.0.0"
  name: "reference_apps_sam_mcu"
  type: "application"
  status: "production"
  required: false
  version: "1.0.0"

  dependencies:
    - name: "csp"
      type: "package"
      version: "v3.20.0-E1"
    - name: "core"
      type: "package"
      version: "v3.14.0-E1"
    - name: "bsp"
      type: "package"
      version: "3.21.0-E1"
    - name: "usb"
      type: "package"
      version: "v3.11.0-E2"
    - name: "gfx"
      type: "package"
      version: "3.15.3"
    - name: "touch"
      type: "package"
      version: "v3.16.0"
    - name: "net"
      type: "package"
      version: "v3.12.3"
    - name: "wireless_wifi"
      type: "package"
      version: "v3.11.1"
    - name: "CMSIS-FreeRTOS"
      type: "package"
      version: "v10.5.1"
    - name: "wolfssl"
      type: "package"
      version: "v5.7.0"
    - name: "crypto"
      type: "package"
      version: "v3.8.2"
    - name: "cryptoauthlib"
      type: "package"
      version: "v3.7.6"
    - name: "wireless_rnbd"
      type: "package"
      version: "v2.0.3"
